// =============================================================================
// Home / Marketing Page
// =============================================================================
// Public landing page. Shows hero, features, and CTA.
// Nav + footer are provided by the (marketing) layout.
// =============================================================================

import Link from 'next/link';
import type { Metadata } from 'next';
import { APP_NAME, APP_DESCRIPTION } from '@/lib/constants';

export const metadata: Metadata = {
  title: `${APP_NAME} — ${APP_DESCRIPTION}`,
  description: APP_DESCRIPTION,
};

const FEATURES = [
  {
    icon: '✨',
    title: 'AI Generation',
    desc: 'Describe your business and get a complete website generated by AI in seconds.',
  },
  {
    icon: '🎨',
    title: 'Visual Editor',
    desc: 'Drag-and-drop sections, customize themes, and fine-tune every detail.',
  },
  {
    icon: '🚀',
    title: 'One-Click Deploy',
    desc: 'Publish to Vercel, Netlify, Cloudflare, or download the code.',
  },
];

export default function HomePage() {
  return (
    <>
      {/* ─── Hero ─────────────────────────────────────────────── */}
      <section className="mx-auto max-w-5xl px-6 py-24 text-center">
        <h1 className="mb-6 text-5xl font-bold tracking-tight text-neutral-900">
          Build a Professional Website
          <br />
          <span className="text-neutral-400">with Just a Description</span>
        </h1>
        <p className="mx-auto mb-10 max-w-2xl text-lg text-neutral-500">
          Describe your business in plain English and our AI will generate a
          complete, customizable website in seconds. No coding required.
        </p>
        <div className="flex items-center justify-center gap-4">
          <Link
            href="/sign-up"
            className="inline-flex items-center gap-2 rounded-lg bg-neutral-900 px-6 py-3 text-sm font-medium text-white shadow-sm hover:bg-neutral-800"
          >
            ✨ Start Building Free
          </Link>
          <Link
            href="/templates"
            className="inline-flex items-center gap-2 rounded-lg border border-neutral-300 px-6 py-3 text-sm font-medium text-neutral-700 hover:bg-neutral-50"
          >
            Browse Templates
          </Link>
        </div>
      </section>

      {/* ─── Features ─────────────────────────────────────────── */}
      <section id="features" className="border-t border-neutral-200 bg-neutral-50 px-6 py-20">
        <div className="mx-auto max-w-5xl">
          <h2 className="mb-12 text-center text-2xl font-bold text-neutral-900">
            Everything You Need
          </h2>
          <div className="grid grid-cols-1 gap-8 md:grid-cols-3">
            {FEATURES.map((f) => (
              <div key={f.title} className="rounded-xl border border-neutral-200 bg-white p-6">
                <div className="mb-3 text-2xl">{f.icon}</div>
                <h3 className="mb-2 font-semibold text-neutral-900">{f.title}</h3>
                <p className="text-sm text-neutral-500">{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ─── CTA band ─────────────────────────────────────────── */}
      <section className="px-6 py-20 text-center">
        <div className="mx-auto max-w-2xl">
          <h2 className="mb-4 text-2xl font-bold text-neutral-900">
            Ready to build your site?
          </h2>
          <p className="mb-8 text-neutral-500">
            Start free, no credit card required. Upgrade when you need more.
          </p>
          <Link
            href="/sign-up"
            className="inline-flex items-center gap-2 rounded-lg bg-neutral-900 px-6 py-3 text-sm font-medium text-white shadow-sm hover:bg-neutral-800"
          >
            Get Started Free
          </Link>
        </div>
      </section>
    </>
  );
}
