// =============================================================================
// Default Value System — v2
// =============================================================================
export type DefaultValuePath = 'brand'|'brand.name'|'brand.tagline'|'brand.description'|'brand.tone'|'brand.mission'|'brand.vision'|'brand.values'|'brand.personality'|'brand.voice'|'brand.colors'|'brand.typography'|'theme'|'theme.preset'|'theme.colors'|'theme.typography'|'pages'|'pages.sections'|'sections'|'sections.animations'|'sections.images'|'sections.items'|'sections.features'|'sections.testimonials'|'sections.members'|'sections.plans'|'sections.steps'|'sections.links'|'sections.posts'|'sections.logos'|'sections.columns'|'sections.tabs'|'seo'|'seo.metaTitle'|'seo.metaDescription'|'seo.keywords'|'seo.ogImage'|'seo.jsonLd'|'settings'|'settings.language'|'settings.socialLinks'|'images'|'images.src'|'images.alt'|'animations'|'items'|'features'|'values'|'keywords';
const D: Record<string, unknown> = { 'brand': { name:'Untitled Business', tagline:'Empowering Your Success', description:'A professional business dedicated to delivering exceptional value to our clients.', tone:'professional', mission:'To deliver exceptional value through innovative solutions and unwavering commitment to quality.', vision:'To be the leading provider in our industry.', values:['Integrity','Innovation','Customer Focus','Quality','Teamwork'], personality:['Professional','Trustworthy','Innovative'], voice:{ tone:['Professional','Approachable','Confident'], style:'Clear and compelling professional communication' }, colors:{ primary:'#2563EB',secondary:'#7C3AED',accent:'#F59E0B',background:'#FFFFFF',surface:'#F8FAFC',text:'#0F172A',textSecondary:'#64748B',border:'#E2E8F0' }, typography:{ heading:'Inter',body:'Inter',mono:'JetBrains Mono' } }, 'brand.colors': { primary:'#2563EB',secondary:'#7C3AED',accent:'#F59E0B',background:'#FFFFFF',surface:'#F8FAFC',text:'#0F172A',textSecondary:'#64748B',border:'#E2E8F0' }, 'brand.typography': { heading:'Inter',body:'Inter',mono:'JetBrains Mono' }, 'theme': { preset:'professional', mode:'light', colors:{}, typography:{}, spacing:{}, borderRadius:{}, shadows:{}, animations:{ enabled:true, duration:300, easing:'ease-out' } }, 'seo': { metaTitle:'', metaDescription:'', keywords:[], ogImage:null, ogType:'website', twitterCard:'summary_large_image', noIndex:false, noFollow:false, jsonLd:[], sitemap:true }, 'settings': { language:'en', direction:'ltr', favicon:null, socialLinks:{}, customCss:'', customJs:'', googleAnalyticsId:null, facebookPixelId:null }, 'animations': [{ type:'fadeIn', duration:500, delay:0, easing:'ease-out', once:true }], 'sections.animations': [{ type:'fadeIn', duration:500, delay:0, easing:'ease-out', once:true }], 'images': [{ src:'/placeholder.svg', alt:'Placeholder image', width:800, height:600 }] };
export function getDefaultValue(path: DefaultValuePath): unknown { if (path in D) return safeClone(D[path]); const parts = path.split('.'); while (parts.length > 0) { parts.pop(); const pp = parts.join('.'); if (pp in D) { const pv = D[pp]; if (typeof pv === 'object' && pv !== null) return (pv as Record<string, unknown>)[path.split('.').pop()!]; } } if (['features','values','keywords','links','posts','logos','columns','tabs','items','members','plans','steps'].includes(path)) return []; return undefined; }
export function getDefaultBrand(): Record<string, unknown> { return safeClone(D['brand']) as Record<string, unknown>; }
export function getDefaultTheme(industry?: string): Record<string, unknown> { return safeClone(D['theme']) as Record<string, unknown>; }
export function getDefaultSEO(businessName?: string): Record<string, unknown> { const s = safeClone(D['seo']) as Record<string, unknown>; if (businessName) { s.metaTitle = `${businessName} — Professional Website`; s.metaDescription = `Welcome to ${businessName}. We provide exceptional services.`; } return s; }
export function getDefaultSettings(): Record<string, unknown> { return safeClone(D['settings']) as Record<string, unknown>; }
export function getDefaultAnimations(): Array<Record<string, unknown>> { return safeClone(D['animations']) as Array<Record<string, unknown>>; }
export function getDefaultImages(count: number = 1): Array<Record<string, unknown>> { const imgs = safeClone(D['images']) as Array<Record<string, unknown>>; if (count <= 1) return imgs; return Array.from({ length: count }, (_, i) => ({ ...imgs[0], alt: `Placeholder image ${i+1}` })); }
export function needsDefault(value: unknown): boolean { return value === null || value === undefined || (Array.isArray(value) && value.length === 0); }
function safeClone<T>(value: T): T { if (typeof structuredClone === 'function') { try { return structuredClone(value); } catch { /* fall through */ } } return JSON.parse(JSON.stringify(value)); }
