// =============================================================================
// Prompt Templates — v2
// =============================================================================
export const JSON_ONLY_INSTRUCTION = `You are a JSON compiler. Output ONLY valid RFC8259 JSON. No markdown. No code fences. No backticks. No explanations. No comments. No trailing commas. No omitted commas. No natural language outside the JSON.`;
export const BRAND_SYSTEM_PROMPT = `${JSON_ONLY_INSTRUCTION}\n\nYou are an expert brand strategist. Given a business description, generate a complete brand identity.\n\nReturn ONLY this exact JSON structure (no extra fields):\n{\n  "name": "Business name",\n  "tagline": "8-12 word compelling tagline",\n  "description": "2-3 sentence brand description",\n  "tone": "professional | casual | luxury | creative | corporate | playful | authoritative | friendly | minimal | bold",\n  "mission": "One sentence mission statement",\n  "vision": "One sentence vision statement",\n  "values": ["3-5 core values as strings"],\n  "personality": ["3-5 brand personality traits as strings"],\n  "voice": { "tone": ["2-3 tone descriptors"], "style": "One sentence style description" }\n}`;
export function buildBrandPrompt(p: {description:string;industry:string;businessType:string;businessName?:string;tone?:string}): string { return [`Business: ${p.businessName||'Not provided'}`,`Description: ${p.description}`,`Industry: ${p.industry}`,`Type: ${p.businessType}`,`Tone: ${p.tone||'professional'}`].join('\n'); }
export const THEME_SYSTEM_PROMPT = `${JSON_ONLY_INSTRUCTION}\n\nYou are an expert UI/visual designer. Generate a complete theme.\n\nReturn ONLY:\n{\n  "preset": "professional | minimal | creative | bold | elegant | playful | corporate | luxury",\n  "mode": "light | dark",\n  "colors": { "primary": "hex", "secondary": "hex", "accent": "hex", "background": "hex", "surface": "hex", "text": "hex", "textSecondary": "hex", "border": "hex" },\n  "typography": { "heading": "Google Font", "body": "Google Font", "mono": "Google Font" },\n  "borderRadius": { "sm": "4px", "md": "8px", "lg": "12px", "xl": "16px", "full": "9999px" },\n  "shadows": { "sm": "0 1px 2px rgba(0,0,0,0.05)", "md": "0 4px 6px rgba(0,0,0,0.07)", "lg": "0 10px 15px rgba(0,0,0,0.1)" }\n}`;
export function buildThemePrompt(p: {businessName:string;industry:string;brandTone:string;brandColors?:any;brandTypography?:any}): string { return [`Business: ${p.businessName}`,`Industry: ${p.industry}`,`Brand tone: ${p.brandTone}`,p.brandColors?`Colors: ${JSON.stringify(p.brandColors)}`:'',p.brandTypography?`Typography: ${JSON.stringify(p.brandTypography)}`:''].filter(Boolean).join('\n'); }
export const PAGES_SYSTEM_PROMPT = `${JSON_ONLY_INSTRUCTION}\n\nYou are an expert information architect. Determine optimal page structure.\n\nReturn ONLY:\n{ "pages": [{ "slug": "url-friendly-name", "title": "Page title", "metaTitle": "SEO meta title (max 60 chars)", "metaDescription": "SEO meta description (max 160 chars)", "isHome": true }] }`;
export function buildPagesPrompt(p: {businessName:string;industry:string;businessType:string;tone:string;brandDescription:string;requestedPages?:string[]}): string { return [`Business: ${p.businessName}`,`Industry: ${p.industry}`,`Type: ${p.businessType}`,`Tone: ${p.tone}`,`Description: ${p.brandDescription}`,p.requestedPages?.length?`Requested pages: ${p.requestedPages.join(', ')}`:''].filter(Boolean).join('\n'); }
export const SECTIONS_SYSTEM_PROMPT = `${JSON_ONLY_INSTRUCTION}\n\nYou are an expert web designer. Given a business and page definition, generate all sections.\n\nReturn ONLY:\n{ "sections": [{ "type": "hero|features|testimonials|pricing|faq|contact|gallery|team|stats|cta|newsletter|footer|navbar|blog|video|logoCloud|map|timeline|portfolio|accordion|tabs|splitSection|comparisonTable|socialProof", "layout": "default|centered|split|grid|masonry|carousel|cards|banner|sidebar|fullscreen", "order": 0, "content": { "headline": "...", "subheadline": "...", ... } }] }`;
export function buildSectionsPrompt(p: {businessName:string;businessType:string;industry:string;tone:string;pageSlug:string;pageTitle:string;isHome:boolean;brandDescription:string}): string { return [`Business: ${p.businessName}`,`Type: ${p.businessType}`,`Industry: ${p.industry}`,`Tone: ${p.tone}`,`Page: ${p.pageTitle} (${p.pageSlug})${p.isHome?' — HOME':''}`,p.isHome?'This is the HOME page. Generate hero first, then features, testimonials, stats, cta. Include navbar and footer.':''].filter(Boolean).join('\n'); }
export const SEO_SYSTEM_PROMPT = `${JSON_ONLY_INSTRUCTION}\n\nYou are an SEO specialist. Generate complete SEO metadata.\n\nReturn ONLY:\n{ "metaTitle": "Global meta title (max 60 chars)", "metaDescription": "Global meta description (max 160 chars)", "keywords": ["5-10 relevant SEO keywords"], "ogImage": null or "URL", "ogType": "website", "twitterCard": "summary_large_image", "noIndex": false, "noFollow": false, "jsonLd": [{ "type": "Organization|WebSite|LocalBusiness", "data": { ... } }], "sitemap": true }`;
export function buildSEOPrompt(p: {businessName:string;description:string;industry:string;businessType:string;pages:Array<{slug:string;title:string;metaTitle:string;metaDescription:string}>;language:string}): string { return [`Business: ${p.businessName}`,`Description: ${p.description}`,`Industry: ${p.industry}`,`Type: ${p.businessType}`,`Language: ${p.language}`,`Pages: ${p.pages.map(pg=>`${pg.title} (${pg.slug})`).join(', ')}`].join('\n'); }
export const IMAGE_SYSTEM_PROMPT = `${JSON_ONLY_INSTRUCTION}\n\nYou are an expert at writing image generation prompts.\n\nReturn ONLY:\n{ "images": [{ "sectionIndex": 0, "sectionType": "hero", "queries": [{ "query": "Detailed image prompt...", "alt": "Accessible alt text...", "style": "photorealistic|illustration|abstract|minimal|artistic" }] }] }`;
export function buildImagePrompt(p: {businessName:string;industry:string;businessType:string;tone:string;sections:Array<{index:number;type:string;headline?:string;description?:string}>}): string { return [`Business: ${p.businessName}`,`Industry: ${p.industry}`,`Type: ${p.businessType}`,`Tone: ${p.tone}`,`Sections:\n${p.sections.map(s=>`Section ${s.index} (${s.type}): ${s.headline||''} — ${s.description||''}`).join('\n')}`].join('\n'); }
